version: 2.1
jobs:
  build:
    docker:
    - image: docker:18.09
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build Image
        command: docker build -t $CIRCLE_PROJECT_REPONAME .
    - run:
        name: Tag Image
        command: |
          set -x
          DOCKER_IMAGE=${DOCKER_IMAGE:-$DOCKER_REPO/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME}
          TAG=build-$CIRCLE_BUILD_NUM
          docker tag $CIRCLE_PROJECT_REPONAME $DOCKER_IMAGE:build-$CIRCLE_BUILD_NUM
          docker tag $CIRCLE_PROJECT_REPONAME $DOCKER_IMAGE:$CIRCLE_BRANCH
          docker tag $CIRCLE_PROJECT_REPONAME $DOCKER_IMAGE:$CIRCLE_SHA1
          [[ "$CIRCLE_BRANCH" == "master" ]] && docker tag $CIRCLE_PROJECT_REPONAME $DOCKER_IMAGE:latest || true
    - run:
        name: Push to Repo
        command: |
          DOCKER_IMAGE=${DOCKER_IMAGE:-$DOCKER_REPO/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME}
          docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_REPO
          docker push $DOCKER_IMAGE
  deploy:
    working_directory: /tmp/project
    docker:
    - image: bitnami/kubectl
      user: root
    steps:
    - run:
        name: "Deploy on cluster"
        command: |
          DOCKER_IMAGE=${DOCKER_IMAGE:-$DOCKER_REPO/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME}
          echo $KUBE_CONFIG | base64 -d > /tmp/kubeconfig.yml
          export KUBECONFIG=/tmp/kubeconfig.yml
          kubectl -n sites patch deployment ${CIRCLE_PROJECT_REPONAME//\./-} -p '{"spec":{"template":{"spec":{"imagePullSecrets":[{"name":"docker-serve-dns"}],"containers":[{"name":"'${CIRCLE_PROJECT_REPONAME//\./-}'","image":"'"$DOCKER_IMAGE:$CIRCLE_SHA1"'"}]}}}}'
workflows:
  version: 2
  main:
    jobs:
    - build:
        context: org-global
        filters:
          branches:
            only: /.*/
          tags:
             only: /.*/
    - deploy:
        requires:
        - build
        context: org-global
        filters:
          branches:
            only: /.*/
          tags:
             only: /.*/